
services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama    # <-- Only this
    networks:
      - llm-docker-setup_default
    restart: always


  postgres:
    image: postgres:16-alpine
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    env_file:
      - .env
    networks:
      - llm-docker-setup_default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -p ${POSTGRES_PORT} -d ${POSTGRES_DATABASE} -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  # minio:
  #   image: minio/minio:latest
  #   container_name: minio
  #   restart: unless-stopped
  #   ports:
  #     - "${MINIO_PORT_API}:9000"
  #     - "${MINIO_PORT_UI}:9001"
  #   environment:
  #     MINIO_HOST: ${MINIO_HOST}
  #     MINIO_ROOT_USER: ${MINIO_ROOT_USER}
  #     MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
  #     MINIO_PORT_API: ${MINIO_PORT_API}
  #     MINIO_PORT_UI: ${MINIO_PORT_UI}
  #   entrypoint: sh
  #   command: >
  #     -c '
  #     mkdir -p /data/warehouse &&
  #     mkdir -p /data/datalake &&
  #     mkdir -p /data/lake-fs &&
  #     mkdir -p /data/mlflow &&
  #     /usr/bin/minio server /data --console-address ":$$MINIO_PORT_UI"'
  #   volumes:
  #     - ./minio_data:/data
  #   networks:
  #     - llm-docker-setup_default
  #   healthcheck:
  #     test: ["CMD-SHELL", "curl -fs http://localhost:9000/minio/health/live || exit 1"]
  #     interval: 30s
  #     timeout: 5s
  #     retries: 3
  #     start_period: 5s

  # mlflow:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.mlflow
  #   container_name: mlflow
  #   environment:
  #     AWS_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
  #     AWS_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
  #     BACKEND_STORE_URI: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_URL}:${POSTGRES_PORT}/${POSTGRES_DATABASE}
  #     MLFLOW_S3_ENDPOINT_URL: http://${MINIO_HOST}:${MINIO_PORT_API}
  #     MLFLOW_S3_IGNORE_TLS: "true"
  #   ports:
  #     - "${MLFLOW_PORT}:5000"
  #   networks:
  #     - llm-docker-setup_default
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #     minio:
  #       condition: service_healthy
  #   healthcheck:
  #     test: ["CMD-SHELL", "curl -fs ${MLFLOW_SERVER_URL}/health || exit 1"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 3
  #   command: >
  #     mlflow server
  #     --backend-store-uri postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_URL}:${POSTGRES_PORT}/${POSTGRES_DATABASE}
  #     --host 0.0.0.0
  #     --serve-artifacts
  #     --artifacts-destination s3://${MLFLOW_BUCKET_NAME}
  #     --gunicorn-opts "--log-level debug --timeout 900 --graceful-timeout 120"

  mcp_server:
    build:
      context: .
      dockerfile: Dockerfile.mcp
    ports:
      - "8001:8000"
    networks:
      - llm-docker-setup_default
    depends_on:
      - postgres
    environment:
      APP_MODULE: src.pg_mcp:app
      POSTGRES_DATABASE: llm_data_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_PORT: 5432
    env_file:
      - .env   # ✅ Load this file

                       

  fastapi:
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - llm-docker-setup_default
    env_file:
      - .env
    depends_on:
      # - mlflow
      - mcp_server
      - ollama
    environment:
      APP_MODULE: src.llm_api:app
      PG_DSN: postgres://admin:password@postgres:5432/llm_data_db
      
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - llm-docker-setup_default
    environment:
      GF_FEATURE_TOGGLES_ENABLE: "accesscontrol"
  
    
  grafana-mcp:
    build:
      context: .
      dockerfile: Dockerfile.grafana-mcp
    ports:
      - "8002:8000"
    container_name: grafana-mcp    
    networks:
      - llm-docker-setup_default
    environment:
      APP_MODULE: src.grafana_mcp:app
    depends_on:
      - grafana


volumes:
  ollama:
  postgres_data:
  minio_data:

networks:
  llm-docker-setup_default:
    name: llm-docker-setup_default
    driver: bridge
